name: publish
on: [push]
jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.NEW_GITHUB_TOKEN }}
    - name: Build the decision tree Docker image
      run: |
        docker build ./decision_tree/ --tag ghcr.io/nuwancw/decision-tree:latest
        docker run ghcr.io/nuwancw/decision-tree:latest
        docker push ghcr.io/nuwancw/decision-tree:latest
        docker build ./download_data/ --tag ghcr.io/nuwancw/download-data:latest
        docker run ghcr.io/nuwancw/download-data:latest
        docker push ghcr.io/nuwancw/download-data:latest
        docker build ./lr/ --tag ghcr.io/nuwancw/lr:latest
        docker run ghcr.io/nuwancw/lr:latest
        docker push ghcr.io/nuwancw/lr:latest
